"""
Track data model for representing temporal object trajectories.

This module defines the Track class, which represents a single object trajectory
across multiple frames with support for multiple coordinate systems (pixel, geodetic,
time-based), visualization styling, and data persistence.
"""

import datetime
from copy import deepcopy
from dataclasses import field
from typing import Annotated, Optional, Self

import numpy as np
import pandas as pd
import pyqtgraph as pg
from numpy.typing import NDArray
from pydantic import Field
from pydantic.dataclasses import dataclass

from vista.detections.detector import PYDANTIC_CONFIG, Detector, dataframe_field
from vista.sensors.sensor import Sensor
from vista.utils.geodetic_mapping import map_geodetic_to_pixel


@dataclass(eq=False, repr=False, config=PYDANTIC_CONFIG)
class Track(Detector):
    """
    Represents a single object trajectory across multiple frames.

    A Track contains temporal position data for a moving object, with support for
    multiple coordinate systems (pixel, geodetic, time-based) and rich visualization
    options. Tracks can be created manually, loaded from files, or generated by
    tracking algorithms.

    Parameters
    ----------
    name : str
        Unique identifier for this track
    frames : NDArray[np.int_]
        Frame numbers where track positions are defined
    rows : NDArray[np.float64]
        Row (vertical) pixel coordinates for each frame
    columns : NDArray[np.float64]
        Column (horizontal) pixel coordinates for each frame
    sensor : Sensor
        Sensor object providing coordinate conversion capabilities

    Attributes
    ----------
    color : str, optional
        Color for track visualization, by default 'g' (green)
    marker : str, optional
        Marker style for current position ('o', 's', 't', 'd', '+', 'x', 'star'),
        by default 'o' (circle)
    line_width : int, optional
        Width of line connecting track points, by default 2
    marker_size : int, optional
        Size of current position marker, by default 12
    visible : bool, optional
        Whether track is visible in viewer, by default True
    tail_length : int, optional
        Number of previous frames to show (0 = all history), by default 0
    complete : bool, optional
        If True, show entire track regardless of current frame, by default False
    show_line : bool, optional
        Whether to draw line connecting track points, by default True
    line_style : str, optional
        Qt line style ('SolidLine', 'DashLine', 'DotLine', 'DashDotLine',
        'DashDotDotLine'), by default 'SolidLine'
    labels : list[set[str]], optional
        One set of text labels per track point, by default an empty list
    extraction_metadata : dict, optional
        Extraction metadata containing image chips and signal detection results.
        Dictionary with keys: 'chip_size' (int), 'chips' (NDArray with shape
        (n_points, diameter, diameter)), 'signal_masks' (boolean NDArray with
        same shape), 'noise_stds' (NDArray with shape (n_points,)), by default None

    Methods
    -------
    __getitem__(slice)
        Slice track by frame range
    get_times()
        Get timestamps for each track point using sensor imagery times
    from_dataframe(df, sensor, name)
        Create Track from pandas DataFrame with coordinate conversion
    length
        Property that returns cumulative Euclidean distance along track
    copy()
        Create a deep copy of the track
    to_csv(file)
        Save track to CSV file
    to_dataframe()
        Convert track to pandas DataFrame

    Notes
    -----
    - Track coordinates can be provided as pixel (row/col) or geodetic (lat/lon/alt)
    - Times can be used instead of frames with automatic conversion via sensor
    - The from_dataframe() method handles coordinate system conversions automatically
    - Track length is computed lazily and cached for performance
    """

    name: Annotated[str, dataframe_field("name", "Track", scalar=True)]

    # Styling attributes
    color: str = dataframe_field("color", "Color", scalar=True, default="g")
    line_width: int = dataframe_field("line_width", "Line Width", scalar=True, default=2)
    marker_size: int = dataframe_field("marker_size", "Marker Size", scalar=True, default=12)
    tail_length: int = dataframe_field("tail_length", "Tail Length", scalar=True, default=0)
    show_line: bool = dataframe_field("show_line", "Show Line", scalar=True, default=True)
    line_style: str = dataframe_field("line_style", "Line Style", scalar=True, default="SolidLine")
    tracker: Optional[str] = dataframe_field("tracker", "Tracker", scalar=True, default=None)

    # Extraction metadata
    extraction_metadata: Optional[dict] = Field(default=None, exclude=True)

    # Uncertainty visualization (2D covariance matrix: [[C00, C01], [C01, C11]])
    covariance_00: Optional[NDArray[np.float64]] = dataframe_field(
        "covariance_00", "Covariance 00", default=None, exclude=True
    )
    covariance_01: Optional[NDArray[np.float64]] = dataframe_field(
        "covariance_01", "Covariance 01", default=None, exclude=True
    )
    covariance_11: Optional[NDArray[np.float64]] = dataframe_field(
        "covariance_11", "Covariance 11", default=None, exclude=True
    )
    show_uncertainty: bool = Field(default=False, exclude=True)

    # Private attributes
    _length: Optional[float] = field(init=False, default=None)

    # Performance optimization: cached data structures
    _brush_params: Optional[tuple] = field(default=None, init=False, repr=False)  # Cached brush parameters

    def __post_init__(self):
        super().__post_init__()

        if self.labels and any(labels != self.labels[0] for labels in self.labels[1:]):
            raise ValueError("Track labels must be identical for every point")
        if self.label_times and any(label_time != self.label_times[0] for label_time in self.label_times[1:]):
            raise ValueError("Track label times must be identical for every point")
        if self.labelers and any(labeler != self.labelers[0] for labeler in self.labelers[1:]):
            raise ValueError("Track labelers must be identical for every point")

    @property
    def label(self) -> set[str]:
        """Return a copy of this track's labels."""
        return self.labels[0].copy() if self.labels else set()

    @property
    def label_time(self) -> Optional[datetime.datetime]:
        """Return when this track was last labeled."""
        return self.label_times[0] if self.label_times else None

    @property
    def labeler(self) -> Optional[str]:
        """Return who last labeled this track."""
        return self.labelers[0] if self.labelers else None

    def set_label(
        self,
        labels: set[str],
        label_time: Optional[datetime.datetime],
        labeler: Optional[str],
    ) -> None:
        """Set track-level label metadata for every point in the track."""
        point_count = len(self)
        self.labels = [labels.copy() for _ in range(point_count)]
        self.label_times = [label_time] * point_count
        self.labelers = [labeler] * point_count

    def __getitem__(self, s):
        track_slice = super().__getitem__(s)

        # Slice extraction metadata if present
        if track_slice.extraction_metadata is not None:
            track_slice.extraction_metadata = {
                "chip_size": track_slice.extraction_metadata["chip_size"],
                "chips": track_slice.extraction_metadata["chips"][s],
                "signal_masks": track_slice.extraction_metadata["signal_masks"][s],
                "noise_stds": track_slice.extraction_metadata["noise_stds"][s],
            }

        # Slice uncertainty data if present
        if track_slice.covariance_00 is not None:
            track_slice.covariance_00 = track_slice.covariance_00[s]
        if track_slice.covariance_01 is not None:
            track_slice.covariance_01 = track_slice.covariance_01[s]
        if track_slice.covariance_11 is not None:
            track_slice.covariance_11 = track_slice.covariance_11[s]

        return track_slice

    def get_index_at_frame(self, frame_num: int) -> int | None:
        """Return the index of the track point at a frame, if present."""
        indices = self._get_indices_at_frame(frame_num)
        return indices[-1] if indices else None

    def get_track_data_at_frame(self, frame_num: int) -> tuple[np.float64, np.float64] | None:
        """
        Get track position at a specific frame using O(1) cached lookup.

        Parameters
        ----------
        frame_num : int
            Frame number to query

        Returns
        -------
        tuple or None
            (row, column) coordinates at this frame, or None if frame not in track
        """
        index = self.get_index_at_frame(frame_num)
        if index is not None:
            return self.rows[index], self.columns[index]
        return None

    def get_visible_indices(self, current_frame):
        """
        Get indices of track points that should be visible at the current frame.

        Parameters
        ----------
        current_frame : int
            Current frame number

        Returns
        -------
        NDArray or None
            Array of indices for visible track points, or None if no points visible
        """
        if self.complete:
            # Show entire track
            return np.arange(len(self.frames))

        # Find points up to current frame
        mask = self.frames <= current_frame

        if self.tail_length > 0:
            # Only show last N frames
            frame_diff = current_frame - self.frames
            mask &= (frame_diff <= self.tail_length) & (frame_diff >= 0)

        indices = np.where(mask)[0]
        return indices if len(indices) > 0 else None

    def invalidate_caches(self):
        """Invalidate cached data structures when track data changes."""
        super().invalidate_caches()
        self._cached_brush = None
        self._brush_params = None
        self._length = None

    def get_pen(self, width=None, style=None):
        return super().get_pen(
            width=self.line_width if width is None else width,
            style=self.line_style if style is None else style,
        )

    def get_brush(self):
        """
        Get cached PyQtGraph brush object for marker fill, creating only if parameters changed.

        Returns
        -------
        pg.mkBrush
            PyQtGraph brush object
        """

        params = (self.color,)

        if self._brush_params != params:
            self._cached_brush = pg.mkBrush(color=self.color)
            self._brush_params = params

        return self._cached_brush

    def has_uncertainty(self) -> bool:
        """
        Check if track has uncertainty data.

        Returns
        -------
        bool
            True if track has all three covariance matrix elements (C00, C01, C11), False otherwise
        """
        return self.covariance_00 is not None and self.covariance_01 is not None and self.covariance_11 is not None

    def get_uncertainty_ellipse_parameters(
        self,
    ) -> Optional[tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]]:
        """
        Convert covariance matrix to ellipse parameters for visualization.

        Computes the semi-major axis length, semi-minor axis length, and rotation angle
        from the 2D covariance matrix at each track point.

        Returns
        -------
        Optional[tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]]
            Tuple of (semi_major_axis, semi_minor_axis, rotation_degrees) arrays, or None if no uncertainty data.
            Rotation is in degrees, counter-clockwise from horizontal (positive column axis).
        """
        if not self.has_uncertainty():
            return None

        # Eigenvalue decomposition of 2x2 covariance matrix
        # For [[C00, C01], [C01, C11]], eigenvalues are:
        # lambda = 0.5 * (C00 + C11 +/- sqrt((C00 - C11)^2 + 4*C01^2))

        trace = self.covariance_00 + self.covariance_11
        discriminant = np.sqrt(
            np.maximum((self.covariance_00 - self.covariance_11) ** 2 + 4 * self.covariance_01**2, 0)
        )

        lambda1 = 0.5 * (trace + discriminant)  # Larger eigenvalue
        lambda2 = 0.5 * (trace - discriminant)  # Smaller eigenvalue

        # Semi-axes are square roots of eigenvalues
        semi_major = np.sqrt(np.maximum(lambda1, 0))
        semi_minor = np.sqrt(np.maximum(lambda2, 0))

        # Rotation angle (in degrees, counter-clockwise from horizontal)
        # arctan2(2*C01, C00 - C11) gives twice the rotation angle
        rotation_rad = 0.5 * np.arctan2(2 * self.covariance_01, self.covariance_00 - self.covariance_11)
        rotation_deg = np.degrees(rotation_rad)

        return semi_major, semi_minor, rotation_deg

    def get_uncertainty_radius(self) -> Optional[NDArray[np.float64]]:
        """
        Compute the geometric mean radius of uncertainty ellipses.

        The geometric mean radius is computed as the fourth root of the covariance
        matrix determinant: sqrt(sqrt(det(Cov))) = sqrt(sqrt(C00*C11 - C01^2)).
        This represents the radius of a circle with the same area as the uncertainty ellipse.

        Returns
        -------
        Optional[NDArray[np.float64]]
            Array of geometric mean radii for each track point, or None if uncertainty data is not available
        """
        if not self.has_uncertainty():
            return None

        # Geometric mean radius = sqrt(det(covariance_matrix))
        det = self.covariance_00 * self.covariance_11 - self.covariance_01**2
        return np.sqrt(np.maximum(det, 0))

    @classmethod
    def normalize_dataframe(cls, df: pd.DataFrame, sensor: Sensor, name: str) -> pd.DataFrame:
        """Normalize temporal and spatial coordinates for a track.

        Temporal normalization is shared with :class:`Detector`. Tracks extend
        it by deriving pixel coordinates from geodetic coordinates when rows
        and columns are not already present.
        """
        df = super().normalize_dataframe(df, sensor, name)
        if "Tracker" in df.columns:
            tracker = df["Tracker"].astype(object)
            df["Tracker"] = tracker.where(tracker.notna() & tracker.ne(""), None)

        has_geodetic = (
            "Latitude (deg)" in df.columns and "Longitude (deg)" in df.columns and "Altitude (km)" in df.columns
        )

        if "Rows" in df.columns and "Columns" in df.columns:
            return df

        if not has_geodetic:
            raise ValueError(
                f"Track '{name}' must have either 'Rows' and 'Columns' columns, "
                "or 'Latitude', 'Longitude', and 'Altitude' columns"
            )

        if not sensor.can_geolocate():
            raise ValueError(
                f"Track '{name}' has geodetic coordinates (Lat/Lon/Alt) but sensor '{sensor.name}' "
                "does not support geolocation."
            )

        rows, columns = map_geodetic_to_pixel(
            df["Latitude (deg)"].to_numpy(),
            df["Longitude (deg)"].to_numpy(),
            df["Altitude (km)"].to_numpy(),
            df["Frames"].to_numpy(),
            sensor,
        )
        df["Rows"] = rows
        df["Columns"] = columns
        return df

    @classmethod
    def from_dataframe(cls, df: pd.DataFrame, sensor: Sensor, name: str | None = None) -> Self:
        """
        Create Track from DataFrame with automatic coordinate conversion.

        Supports multiple input coordinate systems with automatic conversion:
        - Frames or Times → Frames (Times require sensor imagery)
        - Rows/Columns or Lat/Lon/Alt → Rows/Columns (Geodetic requires sensor)

        Priority system: Frames > Times, Rows/Columns > Lat/Lon/Alt

        Parameters
        ----------
        df : pd.DataFrame
            DataFrame containing track data with required columns based on
            coordinate system (see Notes)
        sensor : Sensor
            Sensor object for coordinate conversions
        name : str, optional
            Track name, by default taken from df["Track"]

        Returns
        -------
        Track
            New Track object with converted coordinates

        Raises
        ------
        ValueError
            If required columns are missing or coordinate conversion fails

        Notes
        -----
        Required columns (one set from each group):

        Temporal coordinates (choose one):
            - "Frames" : Frame numbers (preferred)
            - "Times" : Timestamps (requires sensor with imagery times)

        Spatial coordinates (choose one):
            - "Rows" and "Columns" : Pixel coordinates (preferred)
            - "Latitude (deg)", "Longitude (deg)", "Altitude (km)" :
              Geodetic coordinates (requires sensor with geolocation capability)

        Optional styling columns:
            - "Color", "Marker", "Line Width", "Marker Size", "Visible",
              "Complete", "Show Line", "Line Style", "Tail Length", "Labels", "Tracker"
        """
        track = super().from_dataframe(df, sensor, name)
        covariances = (track.covariance_00, track.covariance_01, track.covariance_11)

        if all(covariance is not None and np.all(np.isfinite(covariance)) for covariance in covariances):
            track.show_uncertainty = True
        else:
            track.covariance_00 = None
            track.covariance_01 = None
            track.covariance_11 = None
            track.show_uncertainty = False

        return track

    @property
    def length(self):
        """
        Cumulative Euclidean distance along the track path.

        Computes the sum of pixel distances between consecutive track points.
        Result is cached for performance.

        Returns
        -------
        float
            Total track length in pixels, or 0.0 if track has fewer than 2 points
        """
        if self._length is None:
            if len(self.rows) < 2:
                self._length = 0.0
            else:
                self._length = np.sum(np.sqrt(np.diff(self.rows) ** 2 + np.diff(self.columns) ** 2))
        return self._length

    def copy(self) -> Self:
        """Return a copy with Track-specific fields copied onto the shared Detector copy."""
        track_copy = super().copy()
        track_copy.line_width = self.line_width
        track_copy.tail_length = self.tail_length
        track_copy.show_line = self.show_line
        track_copy.line_style = self.line_style
        track_copy.tracker = self.tracker
        track_copy.extraction_metadata = deepcopy(self.extraction_metadata)
        track_copy.covariance_00 = self.covariance_00.copy() if self.covariance_00 is not None else None
        track_copy.covariance_01 = self.covariance_01.copy() if self.covariance_01 is not None else None
        track_copy.covariance_11 = self.covariance_11.copy() if self.covariance_11 is not None else None
        track_copy.show_uncertainty = self.show_uncertainty
        return track_copy

    def to_dataframe(self) -> pd.DataFrame:
        """Convert track to DataFrame

        Raises:
            ValueError: If geolocation/time requested but imagery is missing required data
        """
        df = super().to_dataframe().drop(columns="Line Thickness")

        # Include geolocation if possible
        if self.sensor and self.sensor.can_geolocate():
            locations = self.sensor.pixel_to_geodetic(self.frames, self.rows, self.columns)
            lons = np.asarray(locations.lon.deg, dtype=np.float64)
            lats = np.asarray(locations.lat.deg, dtype=np.float64)

            invalid = (locations.y.value == 0) & (locations.z.value == 0)
            lons[invalid] = np.nan
            lats[invalid] = np.nan

            df["Longitude (deg)"] = lons
            df["Latitude (deg)"] = lats
            df["Altitude (km)"] = np.asarray(locations.height.to("km").value, dtype=np.float64)
        else:
            # Sensor cannot geolocate - fill with NaN
            df["Latitude (deg)"] = np.full(len(self.frames), np.nan)
            df["Longitude (deg)"] = np.full(len(self.frames), np.nan)
            df["Altitude (km)"] = np.full(len(self.frames), np.nan)

        # Include extraction metadata if present
        if self.extraction_metadata is not None:
            chips = self.extraction_metadata.get("chips")
            masks = self.extraction_metadata.get("signal_masks")
            noise = self.extraction_metadata.get("noise_stds")

            if chips is not None and masks is not None:
                df["Signal Total"] = np.sum(chips * masks, axis=(1, 2))
                df["Signal Pixels"] = np.sum(masks, axis=(1, 2)).astype(float)
            if noise is not None:
                df["Noise Std"] = noise

        # Include uncertainty data if present
        if self.has_uncertainty():
            df["Covariance 00"] = self.covariance_00
            df["Covariance 01"] = self.covariance_01
            df["Covariance 11"] = self.covariance_11

        return df
